### PR TITLE
Remove yum workaround

### PR DESCRIPTION
**Pull request by ficap**

### CODE REVIEW

**Comment by praiskup** [comment]
Looks OK, thanks!

**Comment by pkubatrh** [comment]
@omron93 Any idea why the rhel CI job is getting killed?

**Comment by praiskup** [comment]
[test]

**Comment by omron93** [comment]
@pkubatrh There is 2h timeout for tests. And in this case testing of all dependent images is not finished before timeout is reached.

I've changed it to test only latest version of each dependent image.

[test]

**Comment by pkubatrh** [comment]
Thanks! Tests are passing. Merging

**Pull request merged**
