### PR TITLE
Add support for building and pushing to quay.io/fedora namespace

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds support for building and pushing s2i-core container
and s2i-base container into quay.io/fedora organization.

The repository for s2i-core-fedora container is already created. https://quay.io/repository/fedora/s2i-core-fedora
The repository for s2i-base-fedora container is already created. https://quay.io/repository/fedora/s2i-base-fedora

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Review by zmiklank — APPROVED** [review]
LGTM, thanks!

**Comment by phracek** [comment]
The error needs to be fixed in container-common-scripts. See https://github.com/sclorg/container-common-scripts/pull/243

**Comment by phracek** [comment]
[test]

**Pull request merged**
