### PR TITLE
Update to latest common to make CI work again

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
RHEL CI tests seem to be failing because some of the other PRs updating images (that are being built part of s2i-{core,base} CI) to latest `common` are not yet merged into master. This will be fixed once everything else is merged so we can just re-run the tests later.

**Comment by pkubatrh** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by praiskup** [comment]
Could this be please updated to the latest commons hash first?  I think it is worth it, as the (not)squashing logic is in better shape now.

**Comment by pkubatrh** [comment]
Ah yes, I forgot this PR existed.

Rebased to master and pulled in latest common scripts again.

**Comment by pkubatrh** [comment]
Tests passing, so I will merge this.

**Pull request merged**
