### PR TITLE
Update to Fedora 38

### PR DESCRIPTION
**Pull request by frenzymadness**
Waiting for the final release.

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Test failed on Fedora:
```bash
Complete!
package npm is not installed
Error: building at STEP "RUN INSTALL_PKGS="autoconf   automake   bzip2   gcc-c++   gd-devel   gdb   git   libcurl-devel   libpq-devel   libxml2-devel   libxslt-devel   lsof   make   mariadb-connector-c-devel   npm   openssl-devel   patch   procps-ng   sqlite-devel   unzip   wget   which   zlib-devel" &&   dnf install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&   rpm -V $INSTALL_PKGS &&   dnf clean all -y": while running runtime: exit status 1
make[1]: *** [Makefile:15: base] Error 1
```

**Comment by frenzymadness** [comment]
This is the same issue I've described in https://github.com/sclorg/s2i-python-container/issues/578

npm component was merged into nodejs 6 years ago but the nodejs SRPM still built into npm RPM. 2 months ago, nodejs has been replaced by nodejsXX components and the provided RPM we are interested in is now nodejsXX-npm - the `dnf install npm` still works fine because it's provided by nodejsXX-npm.

So the question is whether the `rpm -V` is really useful for something or just making our lives harder.

**Comment by frenzymadness** [comment]
Fixed the name of the npm package. By the way, Fedora 38 beta is out.
[test]

**Comment by frenzymadness** [comment]
[test]

**Comment by frenzymadness** [comment]
This should have no impact on C8S so I don't consider the failure in the CI as a blocker.

**Review by zmiklank — APPROVED** [review]

**Comment by zmiklank** [comment]
[test]

**Pull request merged**
