### PR TITLE
Move latest fedora release to f40

### PR DESCRIPTION
**Pull request by zmiklank**

### CODE REVIEW

**Comment by hhorak** [comment]
LGTM, but I might not realize all the consequences on TF side, so take my feedback with some respect to not be complete ;)

**Comment by frenzymadness** [comment]
Isn't it too soon? I mean, branching for F40 is today and the target date for release is in the middle of April.

**Comment by zmiklank** [comment]
We need f40 for ruby 3.3 and mariadb 10.11.
I think it would be beneficial for us to start to use and test these images rather sooner, also because of future RHEL images.
But this is planned to be discussed further tomorrow on the container meeting.

**Comment by zmiklank** [comment]
Closing in favor of: https://github.com/sclorg/s2i-base-container/pull/289.

**Pull request closed without merging**
