### PR TITLE
Remove pointless comment about prepare-yum-repositories

### PR DESCRIPTION
**Pull request by frenzymadness**
The script is actually copied and used only on RHEL 7.

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Review by phracek — CHANGES_REQUESTED** [review]
Thanks for the PR. Actually we have Dockerfile.rhel9 files https://github.com/sclorg/s2i-base-container/blob/master/core/Dockerfile.rhel9#L31. Please remove this change as well.

**Comment by frenzymadness** [comment]
> Thanks for the PR. Actually we have Dockerfile.rhel9 files https://github.com/sclorg/s2i-base-container/blob/master/core/Dockerfile.rhel9#L31. Please remove this change as well.

Removed. Please merge it before we add RHEL 10 :smile:

**Comment by phracek** [comment]
[test]

**Pull request merged**
