### PR TITLE
New labels for OSBS

### PR DESCRIPTION
**Pull request by hhorak**
Labels now should follow spec at https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md

### CODE REVIEW

**Comment by omron93** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Pull request merged**
