### PR TITLE
Move to stream 14 as 10 will go EOL at some point

### PR DESCRIPTION
**Pull request by hhorak**
This should also be synced with changes in nodejs image, so do not merge yet.

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by pkubatrh** [comment]
LGTM, lets merge after the tests pass

**Comment by frenzymadness** [comment]
The failure is not related to this change. The problem is that the conu tests in ruby container depend on pytest but I don't see this dependency specified anywhere.

**Review by phracek — APPROVED** [review]
I don't see any blocker here. LGTM.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
> The failure is not related to this change. The problem is that the conu tests in ruby container depend on pytest but I don't see this dependency specified anywhere.

Solving this PR in CI.

**Comment by phracek** [comment]
CI is back and running. Re-testing.

[test]

**Comment by phracek** [comment]
CI is back and running. Re-testing.

[test]

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by phracek** [comment]
Wau. As old Jenkins CI (OpenShift 3.X) as new Jenkins CI (OpenShift 4.X) are PASSing.

Thanks for the PR! I would say awesome test.

**Comment by phracek** [comment]
Tests are passing. Merging.

**Pull request merged**
