### PR TITLE
Add support for building s2i-core and s2i-base from Fedora 39

### PR DESCRIPTION
**Pull request by phracek**

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by zmiklank** [comment]
Is there any reason for moving core and base to f39 just now?

If not, I would rather leave the default one being 38, as main part of our Fedora images is based on 38 and with this change the 38 image will stop getting new updates with rebuilds disabled.

**Comment by phracek** [comment]
@zmiklank @jplesnik is planning to add new Perl-5.38 version that exists only since Fedora 39. Pull request will be available soon.
Only from this reason, I have created this pull request.

**Comment by phracek** [comment]
And python-3.12 also needs Fedora 39.

**Comment by frenzymadness** [comment]
According to the discussion we had at the meeting this week, we should think about how to make it possible to have more than one Fedora version here.

**Comment by phracek** [comment]
q

> According to the discussion we had at the meeting this week, we should think about how to make it possible to have more than one Fedora version here.

I guess, this can be done as separate pull request, right? The issue is here: https://github.com/sclorg/s2i-base-container/issues/279

**Comment by zmiklank** [comment]
Closing in favor of https://github.com/sclorg/s2i-base-container/pull/280.

**Pull request closed without merging**
