### PR TITLE
Calculate available cores from cpu cgroups controller

### PR DESCRIPTION
**Pull request by yrro**
Fixes: https://github.com/sclorg/s2i-base-container/issues/180

### CODE REVIEW

**Comment by frenzymadness** [comment]
The code looks good to me and I've tested that it returns correct values for groups v1 and v2 and that it works for Python 3 and 2.

The only thing I'm curious about is why this problem has not been uncovered by CI? Let's try to run it - [test]

**Comment by frenzymadness** [comment]
What's happening in the tests is a situation when quota is None and therefore has no method `isdigit`. You might use try/except and try to call int() on the variables and expect a ValueError for cases when it's not possible to transfer it to an integer and TypeError for cases when it's None. Or you can use something like `if quota and quota.isdigit() and …`.

**Comment by yrro** [comment]
Well spotted--I think we may as well return `None` as soon as we determine there is no quota set -- there's no point going through the rest of the function. That also means we don't log the "unable to determine cpu quota" message when we _did_ determine that there is no quota.

[test]

**Comment by yrro** [comment]
FYI, the old behaviour in the absence of limits was to query the `cpuset` cgroups controller. Should that behaviour be preserved?

**Comment by frenzymadness** [comment]
[test]

**Comment by frenzymadness** [comment]
I'm not an expert here. I'd like others to take a look as well. Cc @hhorak @pkubatrh @phracek @torsava

**Comment by yrro** [comment]
The failure is...

```
  Testing 'NUMBER_OF_CORES' value...
NUMBER_OF_CORES=
test/run: line 34: [: : integer expression expected
NUMBER_OF_CORES not set.
S2I image 'rhscl/s2i-core-rhel7:1' test FAILED (exit code: 1)
```

... because in the absence of a cpu limit we are failing to output a `NUMBER_OF_CORES` value.

I'll wait for some feedback about whether the `cpuset` controller should be used as a fallback, or ignored, or somehow combined with the `cpu` controller to calculate this value...

**Comment by phracek** [comment]
@gabemontero @lnykryn @kdudka I am not an expert with cgroups, do you have some in your team, who can help us? Any feedback is more then welcome :)

**Comment by gabemontero** [comment]
> @gabemontero @lnykryn @kdudka I am not an expert with cgroups, do you have someone in your team, who can help us? Any feedback is more than welcome :)

Sorry @phracek no immediate recommendations or clear cut pointers to specific folks.  From an openshift team org perspective, perhaps the node team on CoreOS slack (#forum-node ... https://app.slack.com/client/T027F3GAJ/CK1AE4ZCK )

There is also openshift's current doc on node resources .... https://docs.openshift.com/container-platform/4.7/nodes/nodes/nodes-nodes-resources-configuring.html

Although not the same thing, about the closest thing I directly came to this was some JVM heap tuning for the Jenkins image that we borrowed from the the jboss/middleware folks.  But not close enough to draw any bits to this IMO.

@bparees @adambkaplan any additional thoughts?

**Comment by bparees** [comment]
if there is no limit i'd be inclined to use the cpuset value since technically w/ no limit, all the cores are (potentially) available to you.

**Comment by frenzymadness** [comment]
> if there is no limit i'd be inclined to use the cpuset value since technically w/ no limit, all the cores are (potentially) available to you.

That sounds reasonable to me…

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Please use only double quotes and not mix with single quotes in python code.

**Comment by phracek** [comment]
It looks like after modification by this PR the test suite does not work as expected.
See https://github.com/sclorg/s2i-base-container/blob/master/core/test/run#L34

Log from test:
```bash
  Testing 'NUMBER_OF_CORES' value...
NUMBER_OF_CORES=
test/run: line 34: [: : integer expression expected
NUMBER_OF_CORES not set.
```

In some cases, the python script returns None and the bash test fails. Can you please fix it as well?

**Comment by phracek** [comment]
[test]

**Comment by yrro** [comment]
> if there is no limit i'd be inclined to use the cpuset value since technically w/ no limit, all the cores are (potentially) available to you.

How about getting the number of CPUs from both the cpu (quota) and cpuset controllers, and using whichever value is lower?

This way if a container runtime only configures either controller, the value is correct.

I'm trying to think of scenarios where you'd run a container with both controllers configured, and I've come up with:

* I have a dedicated set of CPUs for, say, running databases (0-4) AND I want to run individual database containers with a limit of 2 cores each - I would expect `NUMBER_OF_CORES=2`

I can't think of a useful case for running a container with a cpuset of size 2 and a cpu quota of 4, so using the lower of the two values in this case seems harmless.

I also added a fallback to return the number of CPUs present in the machine. But maybe that's beyond the scope of a script called `cgroup-limits`; I'm happy to remove that if you think it's not desirable.

**Comment by yrro** [comment]
Tests are failing with:

```
11:14:15 -> Pulling image centos:8 before building image from Dockerfile.centos8.
11:14:15 Trying to pull repository docker.io/library/centos ... 
11:14:15 toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Maybe you could use `quay.io/centos/centos` instead?

**Comment by phracek** [comment]
Thank you for this catch.

There are two options for how to fix it. Either as a separate PR or by this PR.
Fixing by this pull request does make sense for me. Can you please do it?

**Comment by yrro** [comment]
Sure - see https://github.com/sclorg/s2i-base-container/pull/209

**Comment by yrro** [comment]
Sorry I just realised you're happy fixing it here - I'll do that then.

**Comment by yrro** [comment]
Sorry I just realised you were ok to do it here. I'll leave that other PR open anyway & rebase this one on top once it's merged.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Let's try one more time. Infra problems.

[test]

**Comment by yrro** [comment]
`centos8` still failing with

```
12:18:04 Trying to pull repository docker.io/library/centos ... 
12:18:54 toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
12:18:54 Pulling image centos:8 failed.
```

I think I need to rebase this PR--doing that now...

**Comment by phracek** [comment]
[test]

**Comment by yrro** [comment]
I've thought about the use of {{multiprocessing}} a bit more and I think it's better to remove the fallback to number of cores.

If I'm deploying a webapp to my OpenShift cluster and forget to set a CPU limit, I'd rather have it fall back to running a single request handler, rather than have it spawn 40 of them and end up using lots of memory unintentionally.

**Comment by yrro** [comment]
That said, `cpuset.cpus.effective` will still contain `[0-39]` in this case. So the fall back to using `multiprocessing` is never used anyway.

**Comment by yrro** [comment]
[test]

**Comment by yrro** [comment]
Guess I can't trigger the tests myself :)

**Comment by phracek** [comment]
> Guess I can't trigger the tests myself :)

No, only owners of the repository

[test]

**Comment by yrro** [comment]
Argh this time it's

```
11:54:58 Step 1/5 : FROM centos/s2i-core-centos8
11:54:58 Trying to pull repository docker.io/centos/s2i-core-centos8 ... 
11:54:58 toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

While building `base/Dockerfile.centos8`.

`base/Dockerfile` succeeds because it's built `FROM quay.io/centos7/s2i-core-centos7` but there doesn't appear to be an equivalent for the centos 8 CI to use.

**Comment by yrro** [comment]
Who can we ask to get a mirror of `s2i-core-centos8` on quay.io?

**Comment by phracek** [comment]
> Who can we ask to get a mirror of `s2i-core-centos8` on quay.io?

I guess a responsible person who owns quay.io/centos organization.

**Comment by phracek** [comment]
[test-all]

**Comment by yrro** [comment]
As of 4f4f13847fd372c304503bc0bf8e11fae6ce9e06, `core/root` is now a symlink into `common` which is a submodule.

I've opened a new PR against the submodule's repo: https://github.com/sclorg/container-common-scripts/pull/237

**Comment by yrro** [comment]
Any chance you can take a look at https://github.com/sclorg/container-common-scripts/pull/237 @phracek?

**Comment by zmiklank** [comment]
Hi, if I understand this correctly, these changes are already present in the container-common-scripts repository. Can this PR be closed?

**Comment by hhorak** [comment]
> Hi, if I understand this correctly, these changes are already present in the container-common-scripts repository. Can this PR be closed?

Let's close it. I'll open a new one to address cgroup-limits script to fail with python traceback when running a container as non-root, but it's not directly related to the changes here.

**Pull request closed without merging**
