### PR TITLE
clean yum cache in rhel8 based s2i-core

### PR DESCRIPTION
**Pull request by pkubatrh**
use yum instead of dnf as yum is now installed in the base image by default

### CODE REVIEW

**Comment by pkubatrh** [comment]
rhel8 failure is from trying to build centos7 based cassandra for some reason, will investigate

**Comment by pkubatrh** [comment]
rhel7 failure is from explicit shadow-utils install and rpm verification scheck even though it comes from base image. Removing in images where it is causing issues in separate PRs.

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
centos7 failure should be fixed by https://github.com/sclorg/mysql-container/commit/0ad545c7e1e8b4eccf5753b24f11f84a23ac1f90 but it seems the CI did not re-trigger

**Comment by phracek** [comment]
LGTM. Thanks. I think it can be merged even w/o CI tests.

**Comment by pkubatrh** [comment]
CI tests green now

**Pull request merged**
