### PR TITLE
move to fedora 35

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by phracek** [comment]
The change itself looks good to me, but did you try to install any package? 
For some reason, I have got an error like mirrorlink not found.

[test]

**Comment by phracek** [comment]
See the same problem here: https://www.reddit.com/r/Fedora/comments/skuu0b/anyone_else_having_trouble_accessing_fedora_35/ and ticket https://pagure.io/fedora-infrastructure/issue/10529

**Comment by phracek** [comment]
> See the same problem here: https://www.reddit.com/r/Fedora/comments/skuu0b/anyone_else_having_trouble_accessing_fedora_35/ and ticket https://pagure.io/fedora-infrastructure/issue/10529

But it looks like it is solved. Let's see

**Comment by pkubatrh** [comment]
Rebased and updated the github action
[test]

**Review by phracek — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
