### PR TITLE
Install npm into the image

### PR DESCRIPTION
**Pull request by hhorak**

### CODE REVIEW

**Comment by pkubatrh** [comment]
s2i-core also needs the workaround applied for the image to be built successfully.

**Comment by omron93** [comment]
Also CentOS `Dockerfile` for base image needs `centos-release-scl` to be installed.

**Comment by hhorak** [comment]
Thanks, hopefully fixed now.

**Comment by omron93** [comment]
LGTM, thanks. Tests are passing, so merging.

**Pull request merged**
