### PR TITLE
WIP: Add GitHub action to build multi-arch docker images

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by frenzymadness** [comment]
Just a note: we are doing something similar for fedora-python-tox container image manually on Travis in these steps:
1. Build images for all architectures on separated machines
2. Push them to Docker hub
3. Pull all of them back from the Docker hub on one machine
4. Create a manifest with all the images and push the manifest back to Docker hub.
5. Test that the manifest contains all the images for all architectures.

Details: https://github.com/fedora-python/fedora-python-tox/blob/master/.travis.yml

**Comment by LinuxSuRen** [comment]
hi @frenzymadness , thanks for providing the information.

**Comment by phracek** [comment]
I created GitHub action here: https://github.com/sclorg/s2i-base-container/blob/master/.github/workflows/build-and-push.yml. It automatically pushes the changes into quay.io registry.

**Comment by LinuxSuRen** [comment]
@phracek thanks for that. I'm going to close this PR.

**Pull request closed without merging**
