### PR TITLE
Add ARM64 support to c9s images

### PR DESCRIPTION
**Pull request by vmuzikar**
With ARM64 increasing market share, it makes sense to have native images for this platform too.

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
Hello @vmuzikar , thank you for the contribution.
Please note, that even though this PR can get merged we are not planning to support non-x86 community images in form of testing.
The x86_64 architecture will still be the only one on which the test will be run. Would you be OK with this approach?

**Comment by vmuzikar** [comment]
@zmiklank Yes, I think it's fine for our use case (Keycloak Operator testing). Thanks.

**Review by pkubatrh — APPROVED** [review]
lgtm

**Pull request merged**
