### PR TITLE
fix fault in fix-permissions where group perms were not set correctly

### PR DESCRIPTION
**Pull request by jim-minter**
Currently this line means: find all files where group read is not set AND group write is not set, and chmod them g+rw.
I think it should be: find all files where group read is not set OR group write is not set, and chmod them g+rw.

Otherwise files which are already g+r do not become g+rw.

This broke the origin extended image ecosystem test.

@hhorak

### CODE REVIEW

**Comment by jim-minter** [comment]
@hhorak assuming this is good to merge, please will you then rebuild and push all builder images affected by this?
@bparees fyi

**Comment by bparees** [comment]
[test]

**Comment by hhorak** [comment]
Yes, thanks for spotting this, I'll merge once we get tests results.

**Comment by jim-minter** [comment]
please delay merging for a moment, I just want to confirm one more thing here

**Comment by jim-minter** [comment]
ok, all good here, tests have passed, please merge if happy

**Comment by bparees** [comment]
tests passed. merging.

**Pull request merged**
