### PR TITLE
Let's build s2i-core and s2i-base container each Tuesday at 1:00

### PR DESCRIPTION
**Pull request by phracek**
This pull request builds s2i-core and s2i-base container each Tuesday at 1:00

@hhorak @frenzymadness @zmiklank Can you please take a look at it and review it?

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by zmiklank** [comment]
Sorry for being lost, but why is this needed, and why rebuild specifically on Tuesdays? Is it a part of a chain-rebuilds?

Otherwise, it seems to me that the PR is functional.

**Comment by zmiklank** [comment]
Sorry for being lost, but why is this needed, and why rebuild specifically on Tuesdays? Is it a part of a chain-rebuilds?

Otherwise, it seems to me that the PR is functional.

**Comment by phracek** [comment]
> Sorry for being lost, but why is this needed, and why rebuild specifically on Tuesdays? Is it a part of a chain-rebuilds?
> 
> Otherwise, it seems to me that the PR is functional.

During Friday's meeting with @frenzymadness @hhorak @pkubatrh We have decided, that we can use GitHub Action to do "chain rebuilds". It means, during Tuesday, we will build s2i-core and s2i-base containers, because they are in the same repository, and the day after or a couple of hours after s2i-core and s2i-base rebuilds we will initiate rebuilds of all our containers across Fedora, CentOS7, and CentOS Stream 9.

**Comment by zmiklank** [comment]
Oh, thanks for the explanation! :)

**Comment by frenzymadness** [comment]
Looks good to me, let's verify that it works and then we can add dependant container images and see that they will build on top of this every week. Good job. Thank you!

**Pull request merged**
