### PR TITLE
Always succeed when running fix-permissions

### PR DESCRIPTION
**Pull request by csrwng**
Exits with success from fix-permissions script ignoring any errors that may have occurred.
https://bugzilla.redhat.com/show_bug.cgi?id=1433027

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal
The fix-permissions script would still fail if the last statement in the script returned a non-zero exit code. This makes sure that a 0 is always returned. Tested with example from bz.

**Comment by bparees** [comment]
lgtm
[test]

**Comment by bparees** [comment]
@hhorak can you pick someone to review/merge this?

**Comment by hhorak** [comment]
Looks good to me, merging. There is also another PR #123 (basically same as #120 which I screw rebase for), where I'll include this change (`exit 0`) as well, but since you're looking at this @csrwng, would you like to comment there as well to see whether it makes sense to you?

**Pull request merged**
