### PR TITLE
Add support for building and testing s2i-core and s2i-base images on RHEL9 host

### PR DESCRIPTION
**Pull request by phracek**
Add support for building and testing s2i-core and s2i-base images on RHEL9 host

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
@pkubatrh PTAL.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Diff between `core/Dockerfile.rhel8` and `core/Dockerfile.rhel9`:

```bash
$ diff core/Dockerfile.rhel8 core/Dockerfile.rhel9
2c2
< FROM registry.access.redhat.com/ubi8:latest
---
> FROM registry.access.redhat.com/ubi9:latest
16c16
<       name="ubi8/s2i-core" \
---
>       name="ubi9/s2i-core" \
29c29
<     PLATFORM="el8"
---
>     PLATFORM="el9"
```

Diff between `base/Dockerfile.rhel8` and `base/Dockerfile.rhel9`:

```bash
$ diff base/Dockerfile.rhel8 base/Dockerfile.rhel9
2c2
< FROM ubi8/s2i-core
---
> FROM ubi9/s2i-core
17c17
<       name="ubi8/s2i-base" \
---
>       name="ubi9/s2i-base" \
23,24c23
< RUN yum -y module enable nodejs:$NODEJS_VER && \
<   INSTALL_PKGS="autoconf \
---
> RUN INSTALL_PKGS="autoconf \
```

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
LGTM

**Pull request merged**
